set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]


set_property PACKAGE_PIN C19 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN E19 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN D19 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN F18 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN E18 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN B20 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN A20 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN A18 [get_ports {seg_en[7]}]


set_property PACKAGE_PIN F15 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN F13 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN F14 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN F16 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN E17 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN C14 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN E13 [get_ports {seg_out[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN Y9 [get_ports rst_n]
set_property PACKAGE_PIN W4 [get_ports in]


set_property IOSTANDARD LVCMOS33 [get_ports hour]
set_property IOSTANDARD LVCMOS33 [get_ports min]
set_property IOSTANDARD LVCMOS33 [get_ports sec]
set_property PACKAGE_PIN T5 [get_ports hour]
set_property PACKAGE_PIN T4 [get_ports min]
set_property PACKAGE_PIN R4 [get_ports sec]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets min_IBUF]


set_property IOSTANDARD LVCMOS33 [get_ports bee_out]
set_property PACKAGE_PIN A19 [get_ports bee_out]


set_property IOSTANDARD LVCMOS33 [get_ports clock_on]
set_property PACKAGE_PIN U5 [get_ports clock_on]
set_property IOSTANDARD LVCMOS33 [get_ports set_hour]
set_property IOSTANDARD LVCMOS33 [get_ports set_min]
set_property PACKAGE_PIN W9 [get_ports set_hour]
set_property PACKAGE_PIN Y7 [get_ports set_min]


set_property IOSTANDARD LVCMOS33 [get_ports {clock1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock_set2[0]}]
set_property PACKAGE_PIN Y8 [get_ports {clock1[3]}]
set_property PACKAGE_PIN AB8 [get_ports {clock1[2]}]
set_property PACKAGE_PIN AA8 [get_ports {clock1[1]}]
set_property PACKAGE_PIN V8 [get_ports {clock1[0]}]
set_property PACKAGE_PIN V9 [get_ports {clock2[3]}]
set_property PACKAGE_PIN AB6 [get_ports {clock2[2]}]
set_property PACKAGE_PIN AB7 [get_ports {clock2[1]}]
set_property PACKAGE_PIN V7 [get_ports {clock2[0]}]
set_property PACKAGE_PIN K14 [get_ports {clock_set1[3]}]
set_property PACKAGE_PIN K13 [get_ports {clock_set1[2]}]
set_property PACKAGE_PIN M20 [get_ports {clock_set1[1]}]
set_property PACKAGE_PIN N20 [get_ports {clock_set1[0]}]
set_property PACKAGE_PIN N19 [get_ports {clock_set2[3]}]
set_property PACKAGE_PIN M17 [get_ports {clock_set2[2]}]
set_property PACKAGE_PIN M16 [get_ports {clock_set2[1]}]
set_property PACKAGE_PIN M15 [get_ports {clock_set2[0]}]
